import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { headers } from 'next/headers'
import WalletProvider from '@pkg/context/WalletProvider'
import IrysUploaderProvider from '@pkg/context/IrysUploaderProvider'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    const cookies = (await headers()).get('cookie')
    return (
        <html lang='en'>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <WalletProvider cookies={cookies}>
                    <IrysUploaderProvider.Evm>{children}</IrysUploaderProvider.Evm>
                </WalletProvider>
            </body>
        </html>
    )
}
